version: 2

jobs:
  test:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                - master